spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/skynet
    redis:
      host: localhost
      port: 6379
  application:
    name: kill-batch-system
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-drop-postgresql.sql
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: kill-9

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true        # SQL 실행문을 눈앞에서 처형한다
    properties:
      hibernate:
        format_sql: true    # SQL을 보기 좋게 줄바꿈해서 출력한다
        highlight_sql: true # SQL을 형형색색으로 치장한다

logging:
  level:
    org.springframework.batch.item.database: DEBUG
    org.springframework.batch.core: DEBUG

rabbitmq:
  queue:
    job-requests: job-requests-queue
  exchange:
    job-requests: job-requests-exchange
  routing-key:
    job-requests: job.launch